### ISSUE TITLE
Ideas for Native WaitSeconds() method in Pedro-Pathing

### ISSUE THREAD

**Issue by Stephen-Onochie** [AnyiLin/Pedro-Pathing-Quickstart#12]
Hey there. My team has had great success with Pedro-Pathing over the last few weeks but we don't know have to natively use wait methods in our PathChains. We tried using the .setPathEndTimeout() method but this didn't seem to work. Any ideas?

**Comment by AnyiLin** [comment]
There are no native wait methods in Pedro Pathing. You could call the hold point method, and then check the path timer until however much time has passed, then break from holding the point or follow a different path

**Comment by Stephen-Onochie** [comment]
Interesting. I'll try this out and see if this works

**Comment by Logan-Nash** [comment]
Anyi recommended a good way for this. another way is checking the t value of the path and setting commands based upon that.
