### ISSUE TITLE
OTOS Localizer BulkRead fix

### ISSUE THREAD

**Issue by woflydev** [AnyiLin/Pedro-Pathing-Quickstart#21]
Changing the `getpose()` method to the following improved loop times and fixed most of the PID issues we ran into after enabling `follower.update()`.

```
@Override
    public Pose getPose() {
        Pose pose = new Pose(otosPose.x, otosPose.y, otosPose.h);

        Vector vec = pose.getVector();
        vec.rotateVector(startPose.getHeading());

        return MathFunctions.addPoses(startPose, new Pose(vec.getXComponent(), vec.getYComponent(), pose.getHeading()));
    } 
```

An alternate solution that I found was changing the bulk cache mode to manual and migrating to a topic-subscriber architecture in the `PoseUpdater` class.

Additionally, (this is a very sketchy workaround until Logan fixes things) it may be worth adding to the docs to initialize the `Follower` instance only after the play button is pressed when using the OTOS. This is because we found that it hallucinates on initialization and can sometimes drift a few inches in any given direction.

**Comment by Logan-Nash** [comment]
Pushed the fix. thanks
