### ISSUE TITLE
OTOSLocalizer rereads from the device every pose access, worsening loop times by tens of milliseconds!

### ISSUE THREAD

**Issue by j5155** [AnyiLin/Pedro-Pathing-Quickstart#8]
Right  now the OTOS localizer reads from the OTOS device over i2c every single time getPose is accessed. This means that every single time you're accessing pose it makes a 3.5ms i2c read, hugely worsening loop times especially when accessing getPose for, say, telemetry data etc. Instead of accessing it every time getPose is called, it would be hugely better for loop times to cache the pose and velocity last read from the sensor in the OTOSLocalizer class, and have the update() function update from the device and update the cache. This would reduce the loop times to that of just a single read per loop, so 3-5ms.

 Also, instead of bulk updating both position and velocity in a single transaction, the OTOS localizer currently reads them on their own from their own functions. This doubles the transaction overhead, likely worsening loop times by another 3ms or so. Instead, it would be optimal to read pose and velocity in one transaction using the getPosVelAcc function and passing by reference, like so:
 ```java 
		SparkFunOTOS.Pose2D otosPose = new SparkFunOTOS.Pose2D();
        SparkFunOTOS.Pose2D otosVel = new SparkFunOTOS.Pose2D();
        SparkFunOTOS.Pose2D otosAcc = new SparkFunOTOS.Pose2D();
        otos.getPosVelAcc(otosPose,otosVel,otosAcc);
        // the pose is now stored in otosPose and the velocity in otosVel
  ```

**Comment by AnyiLin** [comment]
implemented it
